const messages = {
    otpSent: 'OTP sent to your email',
    otpVerified: 'OTP verified successfully',
    passwordChanged: 'Password changed successfully',
    invalidEmail: 'Invalid email format',
    invalidOtp: 'Invalid or expired OTP',
    passwordTooShort: 'Password must be at least 6 characters long',
    userNotFound: 'User not found',
    otpError: 'Error sending OTP',
    otpVerifyError: 'Error verifying OTP',
    passwordChangeError: 'Error changing password',
    validationError: 'Validation Error',
    registrationSuccess: 'User registered successfully.',
    loginSuccess: 'User logged in successfully.',
    tokenInvalid: 'Invalid token',
    tokenNotFound : "Access denied. No token provided",
    // SEC-001: authorization failures are 403 and must read differently from 401,
    // so monitoring can tell "not logged in" from "not permitted".
    forbidden: 'You do not have permission to perform this action',
    // SEC-028: one generic message for every recovery outcome, so the response
    // cannot be used to tell whether an address is registered or what role it holds.
    otpSentIfRegistered: 'If this email is registered, an OTP has been sent',
    invalidResetToken: 'Invalid or expired reset request',
    invalidCredentials: 'Invalid email or password',
    reasonRequired: 'A reason of at least 10 characters is required',
    tooManyRequests: 'Too many attempts. Please try again later',
    passwordPolicy: 'Password does not meet the minimum requirements',
    fullnameRequired: 'Fullname is required',
    invalidMobile: 'Invalid mobile number',
    invalidDateOfBirth: 'Invalid date of birth',
    invalidAge: 'Invalid age',
    invalidBloodGroup: 'Blood group is required',
    invalidEmergencyContact: 'Invalid emergency contact number',
    invalidCity: 'City is required',
    invalidState: 'State is required',
    invalidProfileImage: 'Profile image is required',
    validationError: 'Validation Error',
    serverError: 'Server Error',
    profileNotFound: 'Patient profile not found',
    profileRetrieved: 'Patient profile retrieved successfully',
    profileUpdated: 'Patient profile updated successfully',
    profileCreated: 'Patient profile created successfully',
    messageBlank: 'Message can not be blank',
    faqFetched: 'FAQs fetched successfully',
    emailSent: 'Email sent successfully',
    assessmentIdRequired: 'Assessment Id is required',
    assessmentsFetched: 'Assessments fetched successfully',
    assessmentDetailsFetched: 'Assessment details fetched successfully',
    assessmentCreated: 'Assessment Submitted successfully',
    assessmentCreatingError: 'Error creating assessment',
    doctorsFetched: "Doctors fetched successfully",
    doctorsAdded: "Care Team added successfully",
    appointmentBooked: "Appointment booked successfully",
    careTeamFetched: "Care Team fetched successfully",
    appointmentFetched: "Appointments fetched successfully",
    noAppointmentsFound: "No appointments found",
    noMedicinesFound: "No medicines found",
    medicinesFetched: "Medicines fetched successfully",
    appointmentReschedule: "Appointment rescheduled successfully",
    appointmentCancelled: "Appointment cancelled successfully",
    appointmentDetailsFetched: "Appointment details fetched successfully",
    medicalDetailsFetched: "Medical Records fetched successfully",
    dataFetched: "Data fetched successfully",
    folderFetched: "Folders fetched successfully",
    filesFetched: "Files fetched successfully",
    invalidStateCode: 'Invalid state code',
    prescriptionUpload: "Prescription uploaded successfully",
    itemAddedToCart: "Item added to cart successfully",
    citiesFetched: "Cities List fetched successfully",
    cartDetailsFetched: 'Cart details fetched successfully.',
    labDetailsFetched: 'Lab details fetched successfully.',
    branchesFetched: "Branches List fetched successfully",
    cartItemRemoved: "Cart Item removed successfully",
    prescriptionFetched: 'Prescription URL fetched successfully.',
    prescriptionDeleted: 'Prescription deleted successfully.',
    orderCreated: 'Order created successfully.',
    ordersFetched: 'Orders fetched successfully.',
    labOrderUpdated: 'Lab order updated successfully',
    labOrderNotFound: 'Lab order not found',
    patientDetailsFetched: "Patient details fetched successfully",
    labTestsFetched: "Lab tests fetched successfully.",
    cartNotFound: "Cart is empty!",
    cartUpdated: 'Cart updated successfully',
    cartItemsRemoved: "Cart items has been removed successfully",
    bookingConfirmed: "Your booking has been confirmed",
    paymentLinkGenerated: "Payment link has been generated successfully",
    paymentInitiated: "Payment already initiated",

    paymentFailed: " Payment was attempted but not successful.",
   
    orderProcessAlready: "This order has been already confirmed",
    patientAgeError: "Patient Age must be 18+",
    profileUpdatedButAgeError: "Profile updated, but dependents must be at least 1 year old",
    fileUploaded : "File Uploaded Successfully",
    careNavigatorProfileUpdated: 'Care Navigator profile updated successfully',
    careNavigatorAgeError: "Care Navigator Age must be 18+",
    careNavigatorRetrieved: 'Care Navigator profile retrieved successfully',
    appointmentApproved: "Appointment approved successfully",
    notificationCreated: "Notification created successfully.",
    notificationFetched: "Notifications fetched successfully.",
    notificationError: "An error occurred while processing your request.",
    notificationDeleted: "Notification deleted successfully",
    preEmpCreate : "Employee has been created.",
    preEmpCreateErr : "Some thing is wrong.",
    preEmpRetrieved: 'Employee profile retrieved successfully',
    preEmpProfileUpdated: 'Employee profile updated successfully',
    noOfEmp: 'No of employee fetched successfully',
    statusUpdateEmp: 'Status updated successfully.',
    profileFetched: 'Profile retrieved successfully',
    hrAgeError: "HR Age must be 18+",
    hrProfileUpdated: 'HR profile updated successfully',
    hrRecord: 'HR record fetched successfully',
    vitalDeviceFetched: "Device fetched successfully.",
    userCreated: "User has been created successfully.",
    unauthorize_signup: "Sign-up is not authorized.",
    user_signup: "User's email is already exist.",
    coupon_verified: "Coupon has been verified.",
    user_signup_success: "Your information has been submitted successfully. A verification link has been sent to your email inbox. Please check your email and verify your account using the link provided.",
    sso_invalid_client: "Invalid client id.",
    sso_invalid_parent_client: "Invalid parent client id.",
    sso_invalid_client_secret: "Invalid client secret.",
    sso_api_access_denied: "API access is not enabled for this client.",
    sso_ip_not_whitelisted: "Your IP address is not whitelisted for this client.",
    sso_client_not_under_parent: "The client id does not belong to the given parent client id.",
    sso_user_other_client: "This user belongs to another client.",
    invaliddomain: "Domain is in-valid.",
};

module.exports = { messages };
