const Joi = require('joi');

const socialHistorySchema = Joi.object({
    smoking: Joi.string().valid('Past', 'Present', 'Never').allow(''),
    drinking: Joi.string().valid('Past', 'Present', 'Never').allow(''),
    drugs: Joi.string().valid('Past', 'Present', 'Never').allow(''),
    regular_exercise: Joi.string().valid('Past', 'Present', 'Never').allow(''),
    sexually_active: Joi.string().valid('Past', 'Present', 'Never').allow(''),
    martial_status: Joi.string().allow(''),
    no_of_children: Joi.number().integer().allow(0),
    job_description: Joi.string().allow(''),
    toxic_substance: Joi.string().allow(''),
});

const sexualEmotionalHistorySchema = Joi.object({
    sexual_transmitted_disease: Joi.string().valid('Yes', 'No').allow(''),
    use_condoms: Joi.string().valid('Yes', 'No').allow(''),
    birth_control: Joi.string().valid('Yes', 'No').allow(''),
    victim_abuse: Joi.string().valid('Yes', 'No').allow(''),
    is_pregnant: Joi.string().valid('Yes', 'No').allow(''),
    delivery_date: Joi.string().allow(''),
    no_of_pregnancy: Joi.number().integer().allow(0),
    type_of_pregnancy: Joi.string().allow(''),
    last_menstrual_period: Joi.string().allow(''),
});

const familyHistorySchema = Joi.object({
    breast_cancer: Joi.string().valid('Yes', 'No').allow(''),
    relation_breast_cancer: Joi.string().allow(''),
    colon_cancer: Joi.string().valid('Yes', 'No').allow(''),
    relation_colon_cancer: Joi.string().allow(''),
    prostate_cancer: Joi.string().valid('Yes', 'No').allow(''),
    relation_prostate_cancer: Joi.string().allow(''),
    skin_cancer: Joi.string().valid('Yes', 'No').allow(''),
    relation_skin_cancer: Joi.string().allow(''),
    ovarian_cancer: Joi.string().valid('Yes', 'No').allow(''),
    relation_ovarian_cancer: Joi.string().allow(''),
    lung_cancer: Joi.string().valid('Yes', 'No').allow(''),
    relation_lung_cancer: Joi.string().allow(''),
    other_cancer: Joi.string().valid('Yes', 'No').allow(''),
    relation_other_cancer: Joi.string().allow(''),
    diabetes: Joi.string().valid('Yes', 'No').allow(''),
    relation_diabetes: Joi.string().allow(''),
    hypertension: Joi.string().valid('Yes', 'No').allow(''),
    relation_hypertension: Joi.string().allow(''),
    heart_disease: Joi.string().valid('Yes', 'No').allow(''),
    relation_heart_disease: Joi.string().allow(''),
    lungs_problem: Joi.string().valid('Yes', 'No').allow(''),
    relation_lungs_problem: Joi.string().allow(''),
    other_problems: Joi.string().valid('Yes', 'No').allow(''),
    relation_other_problems: Joi.string().allow(''),
    alcoholism: Joi.string().valid('Yes', 'No').allow(''),
    relation_alcoholism: Joi.string().allow(''),
    drug_abuse: Joi.string().valid('Yes', 'No').allow(''),
    relation_drug_abuse: Joi.string().allow(''),
});

const createOrUpdatePatientSchema = Joi.object({
    id: Joi.number().optional(),
    fullname: Joi.string().required(),
    email: Joi.string().required(),
    phone: Joi.string().required(),
    dateofbirth: Joi.string().required(),
    gender: Joi.string().required(),
    city: Joi.string().required(),
    state: Joi.string().required(),
    zip_code: Joi.string().required(),
    age: Joi.number().integer().allow(null),
    height: Joi.string().allow(''),
    weight: Joi.string().allow(''),
    bloodgroup: Joi.string().allow(''),
    emergency_contact: Joi.string().allow(''),
    profile_image: Joi.string().allow(''),
    aadharcard: Joi.string().allow(''),
    abha_id: Joi.string().allow(''),
    past_operation_detail: Joi.string().allow(''),
    social_history: socialHistorySchema.allow(null),
    sexual_emotional_history: sexualEmotionalHistorySchema.allow(null),
    symptoms: Joi.array().items(Joi.string()).allow(null),
    vaccinations: Joi.array().items(Joi.string()).allow(null),
    consent: Joi.object().allow(null),
    religious_belief: Joi.object().allow(null),
    medications: Joi.array().items(Joi.string()).allow(null),
    medical_allergies: Joi.array().items(Joi.string()).allow(null),
    health_problems: Joi.array().items(Joi.string()).allow(null),
    family_history: Joi.object().allow(null),
    dependents: Joi.array().allow(null),
});

module.exports = {
    createOrUpdatePatientSchema,
};
