// models/ssoLoginCode.js
const { DataTypes, Model } = require('sequelize');
const { sequelizeDB1 } = require('../config/sequelize');

// one time codes generated by an api client to log a patient in, only the sha256 hash of the code is stored
class SsoLoginCode extends Model {}

SsoLoginCode.init({
    codeHash: {
        type: DataTypes.STRING(64),
        allowNull: false,
        unique: true
    },
    patientId: {
        type: DataTypes.INTEGER,
        allowNull: false
    },
    companyId: {
        type: DataTypes.INTEGER,
        allowNull: false
    },
    expiresAt: {
        type: DataTypes.DATE,
        allowNull: false
    },
    usedAt: {
        type: DataTypes.DATE,
        allowNull: true
    }
}, {
    sequelize: sequelizeDB1,
    tableName: 'ssoLoginCode',
    timestamps: true
});

module.exports = SsoLoginCode;
